baseurl = "https://gift-nae-wedding.firebaseapp.com"
title = "Tanika & Netipun"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->are getting married<!--]--><br />'
  description2 = '<!--[-->Start at 7:09 am<!--]--><br />'
  logo = "fa-heart"

[languages]
[languages.en]
languageName = "English"
weight = 1
